#services:
#  mysql:
#    image: mysql:8.4
#    container_name: mysql_db_docker
#    environment:
#      MYSQL_ROOT_PASSWORD: 3226
#      MYSQL_DATABASE: dct
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 3226
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#    networks:
#      - app-network
#
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:latest
#    container_name: phpmyadmin
#    environment:
#      PMA_HOST: mysql_db_docker
#      PMA_PORT: 3306
#      MYSQL_ROOT_PASSWORD: 3226
#      UPLOAD_LIMIT: 256M  # Increase upload limit for larger SQL files
#    ports:
#      - "8080:80"
#    depends_on:
#      - mysql
#    networks:
#      - app-network
#
#  springboot:
#    build: .
#    container_name: simple_project
#    environment:
#      SERVER_PORT: 8003
##      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db_docker:3306/dct
##      SPRING_DATASOURCE_USERNAME: root
##      SPRING_DATASOURCE_PASSWORD: 3226
#      MYSQL_HOST: mysql
#      MYSQL_PORT: 3306
#      MYSQL_USER: root
#      MYSQL_DB: dct
#      MYSQL_PASSWORD: 3226
##      EMAIL_HOST:
##      EMAIL_PORT:
##      EMAIL_USERNAME:
##      EMAIL_PASSWORD:
##      EMAIL_DOMAIN:
##      CLOUDINARY_API_KEY:
##      CLOUDINARY_API_SECRET:
##      CLOUDINARY_NAME:
#    ports:
#      - "8003:8003"
#    depends_on:
#      - mysql
#
#networks:
#  app-network:
#    driver: bridge
#
#volumes:
#  mysql_data: